# Generated by Django 4.0.4 on 2022-04-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySafeCore', '0002_alter_venueentryexitrecord_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='hkuMember',
        ),
        migrations.AlterField(
            model_name='venue',
            name='type',
            field=models.CharField(choices=[('LT', 'Lecture Theatre'), ('CR', 'Classroom'), ('TR', 'Tutorial Room')], max_length=3),
        ),
        migrations.AlterField(
            model_name='venueentryexitrecord',
            name='exitDatetime',
            field=models.DateTimeField(default=0, null=True),
        ),
    ]
