# Generated by Django 4.0.4 on 2022-05-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudySafeCore', '0003_remove_venue_hkumember_alter_venue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueentryexitrecord',
            name='exitDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
